# render.yaml – Ingenuity Smart Parking (monorepo)

services:
  # ---------- BACKEND DOCKERIZED ----------
  - type: web
    name: ingen-parking-backend
    runtime: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ingen-parking-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ingen-parking-db
          property: connectionString
      - key: POSTGRES_USER
        fromDatabase:
          name: ingen-parking-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: ingen-parking-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: ingen-parking-db
          property: database
      - key: PORT
        value: 8000

  # ---------- FRONTEND STATIC SITE ----------
  - type: web
    name: ingen-parking-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://ingen-parking-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /

databases:
  - name: ingen-parking-db
    plan: free
    postgresMajorVersion: "15"
    databaseName: ingenparking
