# This file defines the services, networks, and volumes for the Ingen Parking
# application using Docker Compose.

services:
  db:
    image: postgres:15
    container_name: ingen-parking-db
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
    container_name: ingen-parking-api
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      - db
    working_dir: /app
    ports:
      - "8000:8000"

volumes:
  db_data:
