# This file defines the Docker services for the Ingenuity Smart Parking project.

services:
  db:
    image: postgres:17.5
    container_name: ingen-parking-db
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # default PostgreSQL port (host:container)
  backend:
    build: ../backend
    container_name: ingen-parking-api
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "8000:8000" # default Flask port (host:container)
volumes:
  db_data:
