# This file defines the services, networks, and volumes for the Ingen Parking application using Docker Compose

services:
  db:
    image: postgres:17.5
    container_name: ingen-parking-db
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # default PostgreSQL port (host:container)

  backend:
    build:
      context: ../backend
    container_name: ingen-parking-api
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      - db
    working_dir: /app
    command: gunicorn app:app --bind 0.0.0.0:8000
    ports:
      - "8000:8000" # default Flask port (host:container)
    volumes:
      - ../backend:/app

volumes:
  db_data:
